### ISSUE TITLE
Error: Command failed: dyld: Library not loaded

### ISSUE THREAD

**Issue by cmarrero01** [Kurtz1993/ionic-minify#14]
Hi, I run ionic build android --minify and I get the next error.

```

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/Marrero/Documents/app/node_modules/mozjpeg-stream/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found
    at ChildProcess.onExit (/Users/Marrero/Documents/app/node_modules/mozjpeg-stream/node_modules/duplex-child-process/index.js:116:12)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
Error: Hook failed with error code 1: /Users/Marrero/Documents/app/hooks/after_prepare/ionic-minify.js
```

**Comment by Kurtz1993** [comment]
Hi, thanks for tbe report.
Does the hook start or does it fail immediately?

**Comment by cmarrero01** [comment]
The entire log is:

```
Running command: /Users/Marrero/Documents/app/hooks/after_prepare/ionic-minify.js /Users/Marrero/Documents/app
Starting minifying your files...
Compressing JS file: app.js
JS file: app.js has been minified!
Compressing JS file: routes.js
JS file: routes.js has been minified!
Compressing JS file: config.js
JS file: config.js has been minified!
Compressing JS file: templates.js
JS file: templates.js has been minified!
Compressing CSS file: material-icons.css
CSS file: material-icons.css has been minified!
Compressing CSS file: style.css
CSS file: style.css has been minified!
Compressing/Minifying .DS_Store resulted in an error and won't be compressed/minified.
Compressing JPG file: 1.jpg
Compressing JPG file: 1_vs.jpg
Compressing JPG file: 2.jpg
Compressing JPG file: 2_vs.jpg
Compressing JPG file: 3.jpg
Compressing JPG file: 4.jpg
Compressing JPG file: 5.jpg
Compressing JPG file: 6.jpg
Compressing JPG file: 7.jpg
Compressing JPG file: 8.jpg
Compressing JPG file: adam.jpg
Compressing PNG file: ben.png
Compressing PNG file: bg_login.png
Compressing PNG file: deportes.png
Compressing PNG file: dinero.png
Compressing PNG file: entretenimiento.png
Compressing PNG file: icon.png
Compressing PNG file: ionic.png
Compressing PNG file: logo_mdz.png
Compressing PNG file: mdz.png
Compressing PNG file: mike.png
Compressing PNG file: max.png
Compressing PNG file: mundo.png
Compressing PNG file: opinion.png
Compressing PNG file: perry.png
Compressing PNG file: personaje.png
Compressing PNG file: sociales.png
Compressing PNG file: sociedad.png
Compressing PNG file: suplementos.png
Compressing PNG file: tv.png
Compressing JS file: AccountCtrl.js
JS file: AccountCtrl.js has been minified!
Compressing JS file: HeaderCtrl.js
JS file: HeaderCtrl.js has been minified!
Compressing JS file: HomeCtrl.js
JS file: HomeCtrl.js has been minified!
Compressing JS file: NewsCtrl.js
JS file: NewsCtrl.js has been minified!
Compressing JS file: NotificationsCtrl.js
JS file: NotificationsCtrl.js has been minified!
Compressing JS file: SectionCtrl.js
JS file: SectionCtrl.js has been minified!
Compressing JS file: TabsCtrl.js
JS file: TabsCtrl.js has been minified!
Compressing JS file: TellUs.js
JS file: TellUs.js has been minified!
Compressing JS file: TvCtrl.js
JS file: TvCtrl.js has been minified!
Compressing JS file: MenuLeftDve.js
JS file: MenuLeftDve.js has been minified!
Compressing JS file: share-dve.js
JS file: share-dve.js has been minified!
Compressing JS file: AnalyticsSvc.js
JS file: AnalyticsSvc.js has been minified!
Compressing JS file: HomeSvc.js
JS file: HomeSvc.js has been minified!
Compressing JS file: PushSvc.js
JS file: PushSvc.js has been minified!
Compressing JS file: SectionsSvc.js
JS file: SectionsSvc.js has been minified!
Compressing JS file: ShareSvc.js
JS file: ShareSvc.js has been minified!
Compressing JS file: UtilsSvc.js
JS file: UtilsSvc.js has been minified!
Compressing JS file: Base64.js
JS file: Base64.js has been minified!
Compressing JS file: httpInteceptor.js
JS file: httpInteceptor.js has been minified!
Compressing CSS file: _backgrounds.css
CSS file: _backgrounds.css has been minified!
Compressing CSS file: _buttons.css
CSS file: _buttons.css has been minified!
Compressing CSS file: _fonts.css
CSS file: _fonts.css has been minified!
Compressing CSS file: _forms.css
CSS file: _forms.css has been minified!
Compressing CSS file: _helpers.css
CSS file: _helpers.css has been minified!
Compressing CSS file: _icons.css
CSS file: _icons.css has been minified!
Compressing CSS file: _ionic_componentes.css
CSS file: _ionic_componentes.css has been minified!
Compressing CSS file: _links.css
CSS file: _links.css has been minified!
Compressing CSS file: _objects.css
CSS file: _objects.css has been minified!
Compressing CSS file: _structural_shadow.css
CSS file: _structural_shadow.css has been minified!
Compressing CSS file: _titles.css
CSS file: _titles.css has been minified!
Compressing CSS file: comments.css
CSS file: comments.css has been minified!
Compressing CSS file: contexts.css
CSS file: contexts.css has been minified!
Compressing CSS file: login.css
CSS file: login.css has been minified!
Compressing CSS file: news.css
CSS file: news.css has been minified!
Compressing CSS file: profile.css
CSS file: profile.css has been minified!
Compressing CSS file: text_decorations.css
CSS file: text_decorations.css has been minified!
Compressing PNG file: quote_arrow.png
Compressing PNG file: quotes_64.png
Compressing PNG file: quotes_64_b.png
Compressing PNG file: shadow_bottom.png
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/Marrero/Documents/app/node_modules/mozjpeg-stream/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found

    at ChildProcess.onExit (/Users/Marrero/Documents/app/node_modules/mozjpeg-stream/node_modules/duplex-child-process/index.js:116:12)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
Error: Hook failed with error code 1: /Users/Marrero/Documents/app/hooks/after_prepare/ionic-minify.js
```

I think its a problem with the image library for png alpha?

**Comment by Kurtz1993** [comment]
I think the same but the error points to the JPG compressor. I'll take a deeper look at this today.

**Comment by Kurtz1993** [comment]
Yes, it seems that the PNG compressor cannot manage too much files, got the same error.
I'll add error handling for this.

**Comment by santekotturi** [comment]
I'm still seeing this error

```
minified $ ionic prepare ios --minify
Running command: /Users/developer/Developer/ionic/minified/hooks/after_prepare/010_add_platform_class.js /Users/developer/Developer/ionic/minified
add to body class: platform-ios
Running command: /Users/developer/Developer/ionic/minified/hooks/after_prepare/ionic-minify.js /Users/developer/Developer/ionic/minified
Starting minifying your files...
Compressing JS file: app.js
JS file: app.js has been minified!
Compressing JS file: controllers.js
JS file: controllers.js has been minified!
Compressing JS file: services.js
JS file: services.js has been minified!
Compressing CSS file: style.css
CSS file: style.css has been minified!
Compressing JPG file: adam.jpg
Compressing PNG file: ben.png
Compressing PNG file: ionic.png
Compressing PNG file: max.png
Compressing PNG file: mike.png
Compressing PNG file: perry.png
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Command failed: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/developer/Developer/ionic/minified/node_modules/mozjpeg-stream/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found
```

**Comment by dabush-eliel** [comment]
Hi,
when running this command:

> "cordova build --release android"

I am also facing this error:

> Compressing/Minifying .DS_Store resulted in an error and won't be compressed/minified.
> Compressing JPG file: desk-laptop-notebook-working.jpg
> Compressing JPG file: desk-office-pen-ruler.jpg
> Compressing JPG file: magazines-desk-work-workspace.jpg
> Compressing JPG file: people-coffee-notes-tea.jpg
> Compressing JPG file: sunglasses-hand-smartphone-desk.jpg
> events.js:85
>       throw er; // Unhandled 'error' event
>             ^
> Error: Command failed: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
>   Referenced from: /Users/elieldabush/Development/my-work-hours/node_modules/mozjpeg-stream/node_modules/mozjpeg/vendor/cjpeg
>   Reason: image not found
> 
>   at ChildProcess.onExit (/Users/elieldabush/Development/my-work-hours/node_modules/mozjpeg-stream/node_modules/duplex-child-process/index.js:116:12)
>     at ChildProcess.g (events.js:199:16)
>     at ChildProcess.emit (events.js:110:17)
>     at maybeClose (child_process.js:1015:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
> Error: Hook failed with error code 1: /Users/elieldabush/Development/my-work-hours/hooks/after_prepare/ionic-minify.js 

ionic version: 
1.7.14

cordova version:
6.0.0

npm version:
2.11.3

Anyone found a solution?

**Comment by Kurtz1993** [comment]
Do you have homebrew installed on your Mac?

Try a brew link libpng. I made some more research on this issue and it seems to have something to do with OS X libraries.
Even when this issue presented with PHP is the same error you're facing:
http://stackoverflow.com/questions/22631026/dyld-library-not-loaded-usr-local-lib-libpng16-16-dylib-with-anything-php-rel

**Comment by dabush-eliel** [comment]
nope.
i installed homebrew then i installed the missing lib:
 brew install libpng
and its working.
thanks!

**Comment by mcwebb** [comment]
I got the same error, easily fixed by updating my version of libpng from 1.6.18 to 1.6.21
`brew upgrade libpng`

**Comment by Kurtz1993** [comment]
I'm glad that the solution was accurate. I'll mark this issue as closed.

**Comment by rinogo** [comment]
Note for others - My `brew` installation kept on installing an older version of `libpng`:

```
$ brew install libpng
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/libpng-1.6.
######################################################################## 100.0%
==> Pouring libpng-1.6.15.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.15: 17 files, 1.3M
```

```
$ brew upgrade libpng
Error: libpng-1.6.15 already installed
```

To get the newer version of `libpng` to install, I had to update `brew`:

```
$ brew update
Checking out files: 100% (3533/3533), done.
==> Migrating Homebrew to v0.9.9
[...]
Removing: /Library/Caches/Homebrew/libpng-1.6.15.yosemite.bottle.tar.gz... (431.4K)
==> Migrating /Library/Caches/Homebrew to /Users/rich/Library/Caches/Homebrew...
==> Deleting /Library/Caches/Homebrew...
Already up-to-date.
$ brew upgrade libpng
==> Upgrading 1 outdated package, with result:
libpng 1.6.21
==> Upgrading libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.21.yosemite.bott
######################################################################## 100.0%
==> Pouring libpng-1.6.21.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.21: 25 files, 1.2M
```
