### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by behrad** [Kurtz1993/ionic-minify#6]
`ionic build ios --release` results:

```
Minifying JS file: zh-cn.js
Minifying JS file: zh-tw.js
Minifying JS file: amd-named.js
/Users/behrad/workspace/navad/node_modules/uglify-js/tools/node.js:76
        files.forEach(function(file){
             ^

TypeError: Cannot read property 'forEach' of undefined
    at Object.exports.minify (/Users/behrad/workspace/navad/node_modules/uglify-js/tools/node.js:76:14)
    at compress (/Users/behrad/workspace/navad/hooks/after_prepare/ionic-minify.js:63:29)
    at /Users/behrad/workspace/navad/hooks/after_prepare/ionic-minify.js:119:11
    at FSReqWrap.oncomplete (fs.js:82:15)
Error: Hook failed with error code 1: /Users/behrad/workspace/navad/hooks/after_prepare/ionic-minify.js
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:195:23
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

ionic info:

```
Cordova CLI: 5.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v4.1.0
Xcode version: Xcode 6.3 Build version 6D570
```

**Comment by Kurtz1993** [comment]
Hmmm... this seems to be an error with the uglify-js module, I'll take a look at this.

**Comment by Kurtz1993** [comment]
4a2a3b3 that make use of specific versions for dependencies, should deal wit this.
