### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by prosenjit-manna** [Kurtz1993/ionic-minify#8]
After added I run ionic run `android --release` get this error also try `ionic prepare android`

`Running command: /Users/username/dev/appname/hooks/after_prepare/ionic-minify.js /Users/username/dev/appname
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at Object.exports.spawn (child_process.js:995:9)
    at Object.exports.spawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:103:31)
    at runScriptViaChildProcessSpawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:189:23)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)`

**Comment by Kurtz1993** [comment]
This is a quirk with UNIX systems. You must apply a chmod -R 755 to the hooks/ folder, then try again, it should work.

**Comment by prosenjit-itobuz** [comment]
Another error

`/Users/username/dev/appname/node_modules/uglify-js/tools/node.js:76
        files.forEach(function(file){
             ^
TypeError: Cannot read property 'forEach' of undefined
    at Object.exports.minify
(/Users/username/dev/appname/node_modules/uglify-js/tools/node.js:76:14)
    at compress
(/Users/username/dev/appname/hooks/after_prepare/ionic-minify.js:63:29)
    at
/Users/username/dev/appname/hooks/after_prepare/ionic-minify.js:119:11
    at FSReqWrap.oncomplete (fs.js:95:15)
Error: Hook failed with error code 1:
/Users/username/dev/appname/hooks/after_prepare/ionic-minify.js
    at
/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:195:23
    at _rejected
(/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when
(/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch
(/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush
(/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)`

Thanks and Regards
------------------------------
Prosenjit Manna
Itobuz technologies Pvt. Ltd
